FROM ubuntu:focal as saxonica-build

ARG DEBIAN_FRONTEND=noninteractive
ARG NB_USER=jovyan
ARG NB_UID=1000

# cache-busting to force rebuild the image in mybinder.org.
RUN echo cache-busting-6

COPY apt.txt /tmp/apt.txt
COPY requirements.txt /tmp/requirements.txt

RUN apt-get update && \
  apt-get install -y $(cat /tmp/apt.txt | tr '\n' ' ') && \
  rm -rf /var/lib/apt/lists/* && \
  pip3 install --no-cache-dir -U -r /tmp/requirements.txt && \
  rm -f /tmp/{apt.txt,requirements.txt}

# Support UTF-8 filename in Python (https://stackoverflow.com/a/31754469)
ENV LC_CTYPE=C.UTF-8
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

# Install tslab
ENV PATH $PATH:${HOME}/.npm-global/bin
RUN mkdir ~/.npm-global &&\
  npm config set prefix '~/.npm-global' &&\
  npm install -g tslab &&\
  tslab install

# Install Python saxonc dependencies
# Hat tip to @danielnaab.
# https://github.com/GSA/fedramp-automation/blob/090e669e2bf177e03117e50e0389d56c422d0271/src/examples/python/Dockerfile
RUN wget -O /tmp/saxon.zip https://www.saxonica.com/saxon-c/libsaxon-HEC-setup64-v1.2.1.zip \
  && unzip /tmp/saxon.zip -d /tmp \
  && (echo "/opt/saxonica" && cat) | ./tmp/libsaxon-HEC-setup64-v1.2.1 \
  && ln -s /opt/saxonica/libsaxonhec.so /usr/lib/libsaxonhec.so \
  && ln -s /opt/saxonica/rt /usr/lib/rt
ENV LD_LIBRARY_PATH=/usr/lib/rt/lib/amd64:$LD_LIBRARY_PATH
# Build the saxon-c Python extension and put on PYTHONPATH
RUN cd /opt/saxonica/Saxon.C.API/python-saxon \
  && pip install cython \
  && python3 saxon-setup.py build_ext -if
ENV PYTHONPATH=/opt/saxonica/Saxon.C.API/python-saxon

# Notes:
# 1. Do not use ENTRYPOINT because mybinder need to run a custom command.
# 2. To use JupyterNotebook, replace "lab" with notebook".
# 3. Set --allow-root in case you want to run jupyter as root.
CMD ["jupyter", "lab", "--ip=0.0.0.0"]